[package]
name = "rustsbi-qemu"
version = "0.1.1"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsbi = { git = "https://github.com/rustsbi/rustsbi.git", rev = "b22338a" }
riscv = "0.8"
embedded-hal = "0.2.7"
spin = "0.9"
lazy_static = { version = "1", features = ["spin_no_std"] }
r0 = "1"
nb = "1"
hashbrown = "0.12"
buddy_system_allocator = "0.8"
uart_16550 = "0.2"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-device-tree = { git = "https://github.com/rustsbi/serde-device-tree.git", rev = "b8c2da9", default-features = false }
