[package]
name = "rustsbi-qemu"
version = "0.1.1"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsbi = { git = "https://github.com/YdrMaster/rustsbi.git", rev = "e17920b" }
riscv = "0.8"
spin = "0.9"
r0 = "1"
buddy_system_allocator = "0.8"
uart_16550 = "0.2"
dtb-walker = { git = "https://github.com/YdrMaster/dtb-walker.git", rev = "0ef2209" }
