[package]
name = "rustsbi-qemu"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsbi = "0.2.2"
buddy_system_allocator = "0.8"
lazy_static = { version = "1", features = ["spin_no_std"] }
spin = "0.9"
riscv = "0.8"
uart_16550 = "0.2"
embedded-hal = "0.2.7"
r0 = "1"
nb = "1"
bitflags = "1"
bit_field = "0.10"
hashbrown = "0.12"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-device-tree = { git = "https://github.com/YdrMaster/serde-device-tree.git", rev = "32d677e", default-features = false }
