[package]
name = "rustsbi-qemu"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsbi = { git = "https://github.com/rustsbi/rustsbi", rev = "af60b02", features = [
    "legacy",
] }
riscv = "0.8"
spin = "0.9"
r0 = "1"
uart_16550 = "0.2"
dtb-walker = "0.1.3"
qemu-exit = "3.0"
