[package]
name = "sbi-rt"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
