[package]
name = "test-kernel"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi-rt = { path = "../sbi-rt" }
riscv = "0.8"
spin = "0.9"
r0 = "1"
lazy_static = { version = "1", features = ["spin_no_std"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-device-tree = { git = "https://github.com/rustsbi/serde-device-tree.git", rev = "b8c2da9", default-features = false }
