name: CI

on:
  push:
  pull_request:

env:
  qemu_version: 7.0.0

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          target: riscv64imac-unknown-none-elf
      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview
          target: riscv64imac-unknown-none-elf

      - name: Cache QEMU
        id: cache-qemu
        uses: actions/cache@v3
        with:
          path: qemu-${{ env.qemu_version }}
          key: qemu-${{ env.qemu_version }}

      - name: Install ninja-build
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Download and Compile QEMU
        if: steps.cache-qemu.outputs.cache-hit != 'true'
        run: |
          wget https://download.qemu.org/qemu-${{ env.qemu_version }}.tar.xz
          tar xf qemu-${{ env.qemu_version }}.tar.xz
          cd qemu-${{ env.qemu_version }}
          ./configure --target-list=riscv64-softmmu
          make -j

      - name: Install QEMU
        run: |
          cd qemu-${{ env.qemu_version }} && sudo make install
          qemu-system-riscv64 --version

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
